source 'http://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass'
  gem 'compass-rails'
  gem 'oily_png'
end

gem 'jquery-rails'



# Authentication
# gem 'devise'
gem 'sorcery'


# File Attachment
gem 'carrierwave'
gem 'remotipart', '~> 0.4'
gem 'mini_magick'


# helper: Model
gem 'simple_form', '~> 2.0.rc'
gem 'kaminari'
gem 'ransack'


# helper: View
# gem 'activeadmin'



group :production do
  gem 'therubyracer'
end

group :development do
  gem "annotate"
end

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
  gem 'machinist', '>= 2.0.0.beta2'
  gem 'minitest'
end
