source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'
# gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
  gem 'compass', '~> 0.12.alpha.0'
end
gem 'sass-rails', "  ~> 3.1.0"

# JavasScript libs
gem 'jquery-rails'
gem 'modernizr-rails'


# Ajax request CoffeeScript support
# gem 'coffeebeans'

# Heroku deployment requirements
group :production do
#   gem 'therubyracer-heroku'
#   gem 'pg'
  gem 'therubyracer'
end


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'


# Authentication
gem 'devise'


# File Attachment
gem 'carrierwave'
gem 'remotipart'


# helper: Model
# gem 'decent_exposure'


# helper: View
# gem "meta_search", '>= 1.1.1'
# gem "inherited_resources", "1.2.2"
# gem 'formtastic'
gem 'activeadmin'


# data processing
# gem 'image_science', git: "git://github.com/asynchrony/image_science.git"
gem 'mini_magick'
# gem 'nokogiri'


group :development do
  gem 'rails-dev-tweaks', '~> 0.5.0'
  gem "annotate"
end

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
